name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate GitHub stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: Lightzzz011
          count_private: true
          include_all_commits: true
          theme: tokyonight
      - name: Commit stats image
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your_email@example.com"
          git add github_stats.png
          git commit -m "Update GitHub stats"
          git push
